name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for TestNG
        run: |
          sudo apt-get update
          sudo apt-get install maven -y
          # Install TestNG dependency manually, if needed
          curl -O https://repo.maven.apache.org/maven2/org/testng/testng/7.1.0/testng-7.1.0.jar

      - name: Run TestNG tests
        run: |
          # You might need to configure classpath to ensure TestNG is available
          java -cp "testng-7.1.0.jar:." org.testng.TestNG testng.xml

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for TestNG
        run: |
          sudo apt-get update
          sudo apt-get install maven -y
          # Install TestNG dependency manually, if needed
          curl -O https://repo.maven.apache.org/maven2/org/testng/testng/7.1.0/testng-7.1.0.jar

      - name: Generate and Upload Test Report
        run: |
          mkdir -p reports
          # Running tests with testng.xml directly
          java -cp "testng-7.1.0.jar:." org.testng.TestNG testng.xml
          mv target/surefire-reports/* reports/

      - name: Upload Test Report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/
