name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and TestNG
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run Gradle build and tests, continue on failure
        run: |
          gradle clean test --continue || true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4  
        with:
          name: allure-results
          path: build/allure-results/
          retention-days: 5

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v4  
        with:
          name: allure-results
          path: build/allure-results/

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless
          curl -o allure.tar.gz -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.tgz
          tar -zxvf allure.tar.gz
          sudo mv allure-2.21.0 /opt/allure
          echo "export PATH=\$PATH:/opt/allure/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Generate Allure Report
        run: |
          allure generate build/allure-results/ --clean -o build/allure-report/

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4  
        with:
          name: allure-report
          path: build/allure-report/
          retention-days: 5

      - name: Deploy Allure Report
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/allure-report/

  deploy:
    name: Deploy Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: job2
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
