name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and TestNG
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          # Copy the config.properties file from src/test/resources to the output directory
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run Gradle build and tests, continue on failure
        run: |
          gradle clean build --continue

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Run Gradle build for report generation
        run: |
          gradle allureReport

      - name: Upload Test Report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/allure-report/
