name: Run API Tests and Generate Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Run Gradle build and tests
        run: gradle clean test

      - name: Generate Allure Report
        run: gradle allureReport

      - name: Upload Test Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-reports
          path: build/allure-report/

  job2:
    name: Upload Final Allure Reports
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-reports
          path: final-allure-reports

      - name: Display Allure Report Files
        run: ls -R final-allure-reports
