name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install dependencies
        run: |
          ./mvnw install

      - name: Run TestNG tests
        run: |
          ./mvnw test -Dtestng.suiteXmlFiles=testng.xml

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install dependencies
        run: |
          ./mvnw install

      - name: Generate and Upload Test Report
        run: |
          mkdir -p reports
          mvn test -Dtestng.suiteXmlFiles=testng.xml
          mv target/surefire-reports/* reports/

      - name: Upload Test Report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/
