name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests-and-generate-report:
    name: API Tests & Generate Report
    runs-on: ubuntu-latest

    services:
      docker:
        image: openjdk:17-jdk-slim
        options: --privileged # If needed to run Docker inside Docker
        ports:
          - 8080:8080  # Expose any required ports

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version  # Ensure Docker is available

      - name: Build Docker image
        run: |
          docker build -t my-api-tests .  # Build Docker image from your Dockerfile

      - name: Run API Tests inside Docker
        run: |
          docker run --rm my-api-tests gradle clean test --continue || true  # Run tests inside Docker container

      - name: Generate Allure Report inside Docker
        run: |
          docker run --rm my-api-tests gradle allureReport || echo "Allure report task failed, but continuing..."

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/allure-results/

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/
