name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests-and-generate-report:
    name: API Tests & Generate Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run API Tests (Continue on Failure)
        run: |
          gradle clean test --continue || true  # Ensures tests complete even if some fail

      - name: Generate Allure Report
        run: |
          gradle allureReport || echo "Allure report task failed, but continuing..."
          ls -R build/reports/allure-report/  # Verify report files exist

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/allure-results/

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/  # Ensure correct upload path
