name: API Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests-and-generate-report:
    name: API Tests & Generate Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Verify Gradle Dependencies
        run: gradle dependencies --stacktrace

      - name: Run API Tests (Continue on Failure)
        run: |
          gradle clean test --continue || true  # Ensures tests complete even if some fail

      - name: Generate Allure Report
        run: |
          gradle allureReport || echo "Allure report task failed, but continuing..."
          ls -R build/reports/allure-report/  # Verify report files exist

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/allure-results/

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/
