name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and TestNG
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Verify Gradle Installation
        run: gradle -v

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run Gradle build and tests
        run: |
          ./gradlew clean test || true  # Ensures the job doesn't fail if tests fail

      - name: List Test Report Files
        run: |
          echo "Checking test reports directory:"
          ls -R build/reports/tests/test/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: test-reports

      - name: List Downloaded Files
        run: |
          echo "Downloaded files:"
          ls -R test-reports

      - name: Upload Final Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: final-test-reports
          path: test-reports
