name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and TestNG
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Create test-results directory
        run: |
          mkdir -p build/test-results

      - name: Run Gradle build and tests, continue on failure
        run: |
          gradle clean build --continue || true

      - name: List All Files in build Directory for Debugging
        run: |
          echo "Listing all files in the build directory:"
          ls -R build/

      - name: Check if test results were created
        run: |
          echo "Checking for test reports in build/test-results:"
          ls -R build/test-results/

      - name: Upload Test Reports as Artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/test-results/

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for artifact to be available (retry mechanism)
        run: |
          echo "Waiting for artifact to be available..."
          # Retry mechanism: check every 5 seconds for 3 minutes (36 checks max)
          for i in {1..36}; do
            echo "Attempt $i to download artifact"
            if actions/download-artifact@v4; then
              break
            else
              echo "Artifact not found, retrying in 5 seconds..."
              sleep 5
            fi
          done

      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: test-reports

      - name: List Downloaded Files
        run: |
          echo "Listing downloaded files:"
          ls -R test-reports

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Verify Allure Plugin Availability
        run: |
          gradle tasks --all

      - name: Run Gradle build for report generation
        run: |
          gradle clean test allureServe || echo "allureServe task not found"  # Use allureServe instead
          ls -R build/allure-results/  # Check if the directory contains the allure results

      - name: Upload Final Test Reports as Artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: final-test-reports
          path: build/allure-report/  # Upload Allure results from the custom path
