name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle build and tests
        run: ./gradlew clean test --info --stacktrace

  upload-reports:
    needs: test
    runs-on: ubuntu-latest
    if: success()  # Only runs if the 'test' job succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Report Directory
        run: |
          echo "Checking if build/reports exists..."
          ls -R build || echo "No reports found!"

      - name: Check Allure Report Directory
        run: |
          echo "Checking Allure results directory:"
          ls -R build/allure-results || echo "No Allure reports found!"

      - name: Upload Test Reports (JUnit)
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test/

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: build/allure-results/
