name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and TestNG
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run Gradle build and tests, continue on failure
        run: |
          gradle clean test --continue || true

      - name: Upload Test Reports as Artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/test-results/

      - name: Upload Allure Results (if available)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/
          if-no-files-found: ignore  # Avoid failure if no results exist

  job2:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle and Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Verify Allure Plugin Availability
        run: gradle tasks --all

      - name: Generate Allure Report
        run: |
          gradle allureReport || echo "Allure Report task not found"
          ls -R build/allure-report/ || echo "No Allure report generated"

      - name: Upload Final Test Reports as Artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: final-test-reports
          path: build/allure-report/
          if-no-files-found: warn  # Avoid job failure if no report exists
