name: Run API Tests and Generate Test Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies for Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip -d /opt/gradle
          echo "export PATH=$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Copy config.properties file
        run: |
          mkdir -p build/resources/test
          cp src/test/resources/config.properties build/resources/test/

      - name: Run Tests and Generate Allure Results
        run: |
          gradle clean test --continue || true

      - name: Upload Test Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/

  job2:
    name: Generate Allure Test Report
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/

      - name: Display Allure Result Files
        run: ls -R build/allure-results/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure Report
        run: |
          allure generate build/allure-results -o build/allure-report --clean

      - name: Upload Final Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/allure-report/
